#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use CSV\Combine\Combine;
use Symfony\Component\Console\Application;

$app = new Application('CSV Combiner', '0.0.1');

$app->add(new Combine);

$app->run();
